"use client";
/* =============================================================================
 * TripAgent — src/components/proposal/ProposalPreview.tsx
 * Rebuilt on pdfjs-dist (2026-09-08, direct request) — the previous
 * version used @react-pdf/renderer's own approach: an <iframe> pointed
 * at the PDF blob, which hands rendering to the BROWSER's built-in PDF
 * plugin. That plugin has its own internal layout heuristics we don't
 * control — confirmed live: at a short/wide box (Proposal Composer's
 * "Fit one page" mode), it silently switched to a multi-page thumbnail
 * grid instead of a normal single-page view, and forcing a `zoom=` hash
 * hint didn't reliably stop it. This component instead loads the SAME
 * generated PDF bytes into pdfjs-dist and paints EVERY page onto its own
 * <canvas> WE own, stacked vertically inside the caller's scrollable
 * container — no native toolbar, no viewer-internal layout modes, and
 * (2026-09-08, follow-up) real continuous scroll restored, which the
 * first single-page version of this component dropped — direct
 * feedback: "is it easier to revert" — no, extending this was the
 * better call, since reverting brings back the background-mismatch and
 * Fit-one-page bugs the canvas rewrite exists to fix.
 *
 * Scroll and the page-nav control stay in sync BOTH ways: scrolling
 * updates which page number is shown, and typing/chevron-ing a page
 * scrolls the container there — `lastScrollReportedPageRef` distinguishes
 * a page change caused by the user's own scroll (don't scroll-snap while
 * they're mid-gesture) from one caused by the nav control (do scroll).
 *
 * Click-through link overlay (2026-09-10) — ProposalDocument.tsx's stays
 * page wraps hotel names/photos in react-pdf's <Link src={url}>, which
 * embeds a REAL PDF link annotation (subtype "Link", a rect + a url) in
 * the generated bytes. This canvas rendering has no annotation layer of
 * its own (unlike a native <iframe>/browser PDF viewer, which paints one
 * automatically) — plain pixels only — so a Link's rect was previously
 * inert here even though it worked in an exported/opened PDF. Reading
 * pdfjs's own `page.getAnnotations()` per rendered page and drawing a
 * plain transparent `<a>` over each Link's rect (converted to this
 * canvas's viewport via `viewport.convertToViewportRectangle`) makes it
 * clickable here too — no separate "where is the hotel block" layout
 * calculation to keep in sync with ProposalDocument.tsx; the rect comes
 * straight from whatever that component actually rendered.
 * ===========================================================================*/
import { useEffect, useRef, useState } from "react";
import { renderProposalPdfBlob } from "../../lib/renderProposalPdf";

type LinkOverlay = { url: string; left: number; top: number; width: number; height: number };

let pdfjsLibPromise: Promise<any> | null = null;
function loadPdfjs() {
  if (!pdfjsLibPromise) {
    pdfjsLibPromise = import("pdfjs-dist").then((mod) => {
      mod.GlobalWorkerOptions.workerSrc = "/pdf.worker.min.mjs";
      return mod;
    });
  }
  return pdfjsLibPromise;
}

export function ProposalPreview({
  document,
  page,
  width,
  pageCount,
  onPageCountChange,
  onPageChange,
  scrollContainerRef,
}: {
  document: React.ReactElement;
  page: number;
  width: number;
  // pageCount — the caller's best GUESS before the real PDF has been
  // parsed (proposal-composer/page.tsx and PublicProposalView.tsx both
  // seed this from ProposalDocument.tsx's PAGE_COUNT, a fixed nominal
  // count that's gone stale now that a stay's card can span more than one
  // physical page — see this component's own realPageCount/
  // onPageCountChange below for the actual fix). Only used as the initial
  // render before pdfjs has told us the TRUE count.
  pageCount: number;
  // onPageCountChange (2026-09-13 fix, real "preview silently drops the
  // last 2 of 6 real pages" repro) — reports the ACTUAL parsed page count
  // back to the caller as soon as pdfjs knows it, so its own page-nav
  // ("X / N") reflects reality instead of the fixed guess above.
  onPageCountChange?: (n: number) => void;
  onPageChange: (n: number) => void;
  scrollContainerRef: React.RefObject<HTMLDivElement | null>;
}) {
  const canvasRefs = useRef<(HTMLCanvasElement | null)[]>([]);
  // pdfDocRef caches the parsed pdfjs document — only re-parsed when
  // `document` (the react-pdf element) itself changes, not on every
  // zoom step or page flip. Written by the FIRST effect and read by the
  // second; both run in registration order within the same commit, so a
  // `document` change is always visible to the second effect on the
  // very render that produced it.
  const pdfDocRef = useRef<{ forDocument: React.ReactElement; promise: Promise<any> } | null>(null);
  const renderTasksRef = useRef<any[]>([]);
  const lastScrollReportedPageRef = useRef<number | null>(null);
  // linkOverlaysByPage — 1-indexed page number -> that page's Link rects,
  // in the SAME CSS-pixel viewport space as the canvas's own style.width/
  // height (see the render effect below), so an overlay div's left/top/
  // width/height can be used verbatim with no further scaling.
  const [linkOverlaysByPage, setLinkOverlaysByPage] = useState<Record<number, LinkOverlay[]>>({});
  // realPageCount (2026-09-13 fix) — null until pdfjs has actually parsed
  // this `document` and told us its TRUE page count; falls back to the
  // caller's `pageCount` guess until then so there's still a reasonable
  // number of canvases to paint into on first render. This is what
  // actually drives how many pages get rendered below — `pageCount` the
  // prop is now only ever the pre-parse placeholder.
  const [realPageCount, setRealPageCount] = useState<number | null>(null);
  const effectivePageCount = realPageCount ?? pageCount;

  useEffect(() => {
    if (pdfDocRef.current?.forDocument === document) return;
    // Reset to the caller's guess while the new document parses — the
    // OLD document's real count would otherwise linger and briefly lie
    // about how many pages this NEW one has.
    setRealPageCount(null);
    // No unmount/document-change cleanup here (2026-09-13 fix, REVERTED
    // 2026-09-14) — this briefly passed an AbortController's signal into
    // renderProposalPdfBlob so a still-in-flight render could be
    // cancelled early. Removed along with renderProposalPdf.ts's own
    // fetch-patching entirely (see that file's own note): once fonts AND
    // images were BOTH made permanently un-abortable (each caches a
    // rejection forever otherwise — the real bug an aborted render was
    // quietly causing), there was nothing left for this signal to
    // actually cancel. A render still in flight when `document` changes
    // again now simply keeps running to completion in the background,
    // same as before either fix existed — its own promise is just never
    // read again once a newer one supersedes it in `pdfDocRef.current`.
    const promise = Promise.all([loadPdfjs(), renderProposalPdfBlob(document)]).then(async ([pdfjsLib, blob]) => {
      const buf = await blob.arrayBuffer();
      return pdfjsLib.getDocument({ data: buf }).promise;
    });
    pdfDocRef.current = { forDocument: document, promise };
    // Report the real count the moment it's known — registered here
    // (not inside the drawing effect below) so it fires as early as
    // possible, one promise tick ahead of the actual per-page drawing
    // loop; that loop's own dependency on `effectivePageCount` (below)
    // is what guarantees it re-runs with every canvas ref actually
    // mounted once this state update commits, regardless of exactly
    // when these two `.then()` callbacks are scheduled relative to each
    // other.
    promise.then((pdfDoc: any) => {
      setRealPageCount(pdfDoc.numPages);
      onPageCountChange?.(pdfDoc.numPages);
    }).catch(() => {});
  }, [document]);

  // Render every page at the caller's target width — matching whatever
  // fit mode/zoom level it computed, same principle the single-page
  // version used, just applied per-canvas here.
  useEffect(() => {
    const entry = pdfDocRef.current;
    if (!entry || width <= 0) return;
    let cancelled = false;

    entry.promise.then(async (pdfDoc: any) => {
      // Loops over the REAL count (pdfDoc.numPages), never the caller's
      // stale guess — effectivePageCount only appears in this effect's
      // OWN dependency array below, purely to force a re-run (with fresh
      // canvas refs already mounted) once realPageCount above updates
      // from the initial guess to the true value.
      const total = pdfDoc.numPages;
      for (let i = 1; i <= total; i++) {
        if (cancelled) return;
        const canvas = canvasRefs.current[i - 1];
        if (!canvas) continue;
        const pageProxy = await pdfDoc.getPage(i);
        if (cancelled) return;

        const unscaledViewport = pageProxy.getViewport({ scale: 1 });
        const scale = width / unscaledViewport.width;
        const viewport = pageProxy.getViewport({ scale });

        const dpr = window.devicePixelRatio || 1;
        canvas.width = Math.round(viewport.width * dpr);
        canvas.height = Math.round(viewport.height * dpr);
        canvas.style.width = `${viewport.width}px`;
        canvas.style.height = `${viewport.height}px`;

        const ctx = canvas.getContext("2d");
        if (!ctx) continue;
        ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

        // Cancel any in-flight render before starting a new one — pdf.js
        // throws if a second render starts on the same canvas mid-render
        // (happens routinely here: width/zoom can change faster than a
        // render completes).
        renderTasksRef.current[i - 1]?.cancel();
        const task = pageProxy.render({ canvasContext: ctx, viewport });
        renderTasksRef.current[i - 1] = task;
        try {
          await task.promise;
        } catch (e: any) {
          if (e?.name !== "RenderingCancelledException") throw e;
        }
        if (cancelled) return;

        // Link annotations (react-pdf's <Link src=...>, e.g. a hotel
        // name/photo in ProposalDocument.tsx's stays page) — read back and
        // converted to this SAME viewport's CSS-pixel space so an overlay
        // <a> lines up with what was actually painted above, whatever
        // ProposalDocument.tsx's own layout happens to be.
        const annotations = await pageProxy.getAnnotations();
        if (cancelled) return;
        const links: LinkOverlay[] = annotations
          // pdf.js only fills in `.url` for a URL it resolves as absolute/
          // safe to auto-follow — a relative link (verified live: our own
          // hotelUrl()'s "/hotel/{hotelKey}" resolves relative to window.
          // location.origin when running in a browser, so this IS absolute
          // in real usage, but pdf.js's own annotationLayer builtin viewer
          // always falls back to `unsafeUrl` too — same discipline here as
          // defence in depth) lands in `.unsafeUrl` instead; `.url` alone
          // silently dropped the annotation entirely (confirmed against a
          // real generated PDF in this session).
          .map((a: any) => ({ ...a, _href: a.url || a.unsafeUrl }))
          .filter((a: any) => a.subtype === "Link" && a._href)
          .map((a: any) => {
            // No convertToViewportRectangle in the installed pdfjs-dist
            // (6.3.289) — confirmed missing there (only
            // convertToViewportPoint(x, y) exists) while building this;
            // transform both rect corners individually instead. The
            // viewport transform can flip the Y axis, so the two
            // transformed corners aren't guaranteed min-then-max — take
            // min/max explicitly rather than assuming point order.
            const [x1, y1, x2, y2] = a.rect;
            const p1 = viewport.convertToViewportPoint(x1, y1);
            const p2 = viewport.convertToViewportPoint(x2, y2);
            const left = Math.min(p1[0], p2[0]);
            const top = Math.min(p1[1], p2[1]);
            return { url: a._href, left, top, width: Math.abs(p2[0] - p1[0]), height: Math.abs(p2[1] - p1[1]) };
          });
        setLinkOverlaysByPage((prev) => ({ ...prev, [i]: links }));
      }
    });

    return () => {
      cancelled = true;
    };
  }, [document, width, effectivePageCount]);

  // External page change (chevron/typed number) → scroll there. Skipped
  // when this exact page number was the one WE just reported from the
  // user's own scroll (see the scroll listener below) — otherwise every
  // scroll tick would fight the user's own scroll gesture with a snap.
  useEffect(() => {
    if (lastScrollReportedPageRef.current === page) return;
    const el = scrollContainerRef.current;
    const target = el?.querySelector(`[data-page="${page}"]`) as HTMLElement | null;
    if (!el || !target) return;
    el.scrollTo({ top: target.offsetTop, behavior: "auto" });
  }, [page, scrollContainerRef]);

  // Scroll → report the page most visible near the container's vertical
  // center, same convention normal PDF viewers use for their own page
  // badge.
  useEffect(() => {
    const el = scrollContainerRef.current;
    if (!el) return;
    function onScroll() {
      const container = scrollContainerRef.current;
      if (!container) return;
      const children = Array.from(container.querySelectorAll<HTMLElement>("[data-page]"));
      const mid = container.scrollTop + container.clientHeight / 2;
      let current = 1;
      for (const child of children) {
        if (child.offsetTop <= mid) current = Number(child.dataset.page);
      }
      lastScrollReportedPageRef.current = current;
      onPageChange(current);
    }
    el.addEventListener("scroll", onScroll);
    return () => el.removeEventListener("scroll", onScroll);
  }, [scrollContainerRef, onPageChange]);

  return (
    <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 16, padding: "16px 0" }}>
      {Array.from({ length: effectivePageCount }, (_, i) => (
        <div key={i} data-page={i + 1} style={{ position: "relative", display: "block" }}>
          <canvas ref={(el) => { canvasRefs.current[i] = el; }} style={{ display: "block" }} />
          {(linkOverlaysByPage[i + 1] || []).map((ov, j) => (
            <a
              key={j}
              href={ov.url}
              target="_blank"
              rel="noreferrer"
              title={ov.url}
              style={{ position: "absolute", left: ov.left, top: ov.top, width: ov.width, height: ov.height, cursor: "pointer" }}
            />
          ))}
        </div>
      ))}
    </div>
  );
}
